version: '3'

# only to be used in development

services:
  populus:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.populus
    environment:
      - DB_ADDR=postgres_populus:5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=liveassist_populus
      - ACCESS_TOKEN_SECRET=UaUs7cC9ckzq2EZdTGTo8voSBrHPuB7R
      - REFRESH_TOKEN_SECRET=hBmarZeJBmi3Hd0FEX4KYrKv7Yb2nlGX
      - DOMAIN=localhost
      - MQ_URL=amqp://lassist:lassist@rabbitmq:5672
      - PORT=8080
    expose:
      - 8080
    depends_on:
      postgres_populus:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  amnis:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.amnis
    environment:
      - DB_ADDR=postgres_amnis:5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=liveassist_amnis
      - ACCESS_TOKEN_SECRET=UaUs7cC9ckzq2EZdTGTo8voSBrHPuB7R
      - MQ_URL=amqp://lassist:lassist@rabbitmq:5672
      - PORT=8080
    expose:
      - 8080
    depends_on:
      postgres_amnis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  nuntius:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.nuntius
    environment:
      - DB_URI=mongodb://mongodb_nuntius:27017/liveassist_nuntius
      - DB_NAME=liveassist_nuntius
      - ACCESS_TOKEN_SECRET=UaUs7cC9ckzq2EZdTGTo8voSBrHPuB7R
      - MQ_URL=amqp://lassist:lassist@rabbitmq:5672
      - PORT=8080
    expose:
      - 8080
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb_nuntius:
        condition: service_started
  verum:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.verum
    environment:
      - ACCESS_TOKEN_SECRET=UaUs7cC9ckzq2EZdTGTo8voSBrHPuB7R
      - REFRESH_TOKEN_SECRET=hBmarZeJBmi3Hd0FEX4KYrKv7Yb2nlGX
      - DOMAIN=localhost
      - PORT=8080
    expose:
      - 8080
  postgres_populus:
    image: postgres
    volumes:
      - populus_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=liveassist_populus
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  postgres_amnis:
    image: postgres
    volumes:
      - amnis_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=liveassist_amnis
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  rabbitmq:
    image: rabbitmq
    volumes:
      - mqdata:/var/lib/rabbitmq
      - mqlogs:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=lassist
      - RABBITMQ_DEFAULT_PASS=lassist
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 5
  mongodb_nuntius:
    image: mongo
    volumes:
      - nuntius_data:/data/db
  nginx:
    image: nginx
    volumes:
      - ./docker/dev/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    depends_on:
      - populus
      - verum
      - amnis

volumes:
  populus_data:
  amnis_data:
  nuntius_data:
  mqdata:
  mqlogs: