version: '3'

# only to be used in development

services:
  populus:
    build:
      dockerfile: ./docker/Dockerfile.populus
    environment:
      - DB_ADDR=postgres:5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=liveassist
      - ACCESS_TOKEN_SECRET=UaUs7cC9ckzq2EZdTGTo8voSBrHPuB7R
      - REFRESH_TOKEN_SECRET=hBmarZeJBmi3Hd0FEX4KYrKv7Yb2nlGX
      - DOMAIN=localhost
    depends_on:
      postgres:
        condition: service_healthy
  verum:
    build:
      dockerfile: ./docker/Dockerfile.verum
    environment:
      - ACCESS_TOKEN_SECRET=UaUs7cC9ckzq2EZdTGTo8voSBrHPuB7R
      - REFRESH_TOKEN_SECRET=hBmarZeJBmi3Hd0FEX4KYrKv7Yb2nlGX
      - DOMAIN=localhost
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=liveassist
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  nginx:
    image: nginx
    volumes:
      - ./docker/dev/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    depends_on:
      - populus
      - verum
