name: Deploy Backend Services

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Install Docker
        uses: docker-practice/actions-setup-docker@master
      -
        name: Create .env file
        run: |
          echo "ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}" >> ./deploy/config/.env
          echo "REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }}" >> ./deploy/config/.env
          echo "DOMAIN=${{ secrets.DOMAIN }}" >> ./deploy/config/.env
      -
        name: Run deploy script
        run: |
          echo "${{ secrets.SSH_KEY }}" > ./key.pem
          export LA_SSH="-i ./key.pem ${{ secrets.SSH_USER }}@${{ secrets.SSH_ADDR }}"
          chmod +x ./deploy.sh
          ./deploy.sh


